import type { PiAgentKind } from '../../shared/pi-agent-kind'

/** Where the fork's pi child lane keeps its live set, which session that set belongs to, and which
 *  registration is allowed to say so.
 *
 *  Pi hands a re-run factory a fresh `pi.events` and re-evaluates this module on /reload, so
 *  neither a module-scope map nor a bus object can hold a session's children: the first is rebuilt
 *  empty by the reload, the second dies with the session. `globalThis` outlives both, and children
 *  are keyed by the session that owns them — a pane shows one session's at a time, and a session
 *  that comes back gets its own back instead of having lost them.
 *
 *  Ownership is decided by the REGISTRATION, never by the process. A child is filed under the
 *  session the reporting registration's own event context named; until that context says anything
 *  the child waits in a shared holding map (so the pane still shows it, and so a session named
 *  later adopts exactly its own), and a registration Pi has shut down can only refuse its own bus. */
export function getPiAgentStatusAsyncSubagentSessionModuleLines(kind: PiAgentKind): string[] {
  if (kind !== 'pi') {
    return []
  }

  return [
    'type PiAsyncSubagentRun = {',
    '  id: string',
    '  agent_type?: string',
    '  description?: string',
    '  /** The workflow run that launched this child, when the bus named one. */',
    '  parent?: string',
    // Why: a child a /reload handed this registration has no end signal left, so the run that
    // launched it is the only thing that can still retire it — which needs to know who reported it.
    '  registration?: object',
    '}',
    'type PiAsyncSubagentRegistration = {',
    '  /** The session this registration’s own event context named, or null while nothing has. */',
    '  sessionKey: string | null',
    '  /** Set by this registration’s own shutdown; a superseded bus is refused from then on. */',
    '  closed: boolean',
    '}',
    'type PiAsyncSubagentState = {',
    '  bySession: Map<string, Map<string, PiAsyncSubagentRun>>',
    // Why: children reported before their registration could name a session. Still this pane’s
    // children — the live set shows them — but not yet attributable to one, so they are not filed
    // under whichever session happened to be on screen.
    '  awaitingSession: Map<string, PiAsyncSubagentRun>',
    '  lastSession: string | null',
    '}',
    // Why: one binding per channel per BUS. The bus object is the identity a binding belongs to:
    // Pi hands a re-run factory its own `pi.events`, so keying the armed state off the evaluation
    // instead leaves a genuinely distinct bus unobserved, while the same bus must never carry two
    // bindings for one channel.
    'type PiAsyncSubagentBusBinding = {',
    '  /** The bus this binding armed. */',
    '  bus: object',
    '  /** The registration its channels report for: the newest run Pi handed this bus. */',
    '  registration: PiAsyncSubagentRegistration',
    '  /** Exactly the callbacks this binding installed, so its own shutdown closes only them. */',
    '  listeners: { channel: string; listener: (payload: unknown) => void }[]',
    '}',
    'declare global { var __orcaPiAsyncSubagents: PiAsyncSubagentState | undefined }',
    'const piAsyncSubagentState: PiAsyncSubagentState = globalThis.__orcaPiAsyncSubagents ??= { bySession: new Map(), awaitingSession: new Map(), lastSession: null }',
    'let piAsyncSubagentBusBindings: PiAsyncSubagentBusBinding[] = []',
    '// Why: the registration whose session the pane is being shown, so a post describes the children',
    '// of the session its own context named rather than of whatever key some other field still holds.',
    '// Display only: which session a child is FILED under is decided by the reporting registration.',
    'let piAsyncSubagentActiveRegistration: PiAsyncSubagentRegistration | null = null',
    '',
    '// Why: the session a run is about, read from the metadata its own event context stamped.',
    'function piAsyncSubagentSessionKey(): string | null {',
    '  const file = sessionMetadata.session_file',
    "  if (typeof file === 'string' && file) return file",
    '  const id = sessionMetadata.session_id',
    "  if (typeof id === 'string' && id) return id",
    '  return null',
    '}',
    '',
    'function piAsyncSubagentBucket(key: string): Map<string, PiAsyncSubagentRun> {',
    '  let bucket = piAsyncSubagentState.bySession.get(key)',
    '  if (!bucket) {',
    '    bucket = new Map()',
    '    piAsyncSubagentState.bySession.set(key, bucket)',
    '  }',
    '  return bucket',
    '}',
    '',
    '// Why: Pi names a session by its transcript file once that exists and by its id before, and both',
    '// name the SAME session — so a bucket opened under the id moves to the file instead of orphaning',
    '// a child that was filed while only the id was known.',
    'function piAsyncSubagentMergeSessionKeys(sessionId: string, sessionFile: string): void {',
    '  const bucket = piAsyncSubagentState.bySession.get(sessionId)',
    '  if (!bucket) return',
    '  const target = piAsyncSubagentBucket(sessionFile)',
    '  for (const entry of bucket) target.set(entry[0], entry[1])',
    '  piAsyncSubagentState.bySession.delete(sessionId)',
    '  if (piAsyncSubagentState.lastSession === sessionId) piAsyncSubagentState.lastSession = sessionFile',
    '}',
    '',
    '// Why: this is where ownership is decided. A registration learns which session it serves from its',
    '// OWN event context, and only then do the children it reported — in the window before any context',
    '// named one — leave the holding map for that session’s bucket.',
    'function piAsyncSubagentNoteSession(ctx: unknown, registration: PiAsyncSubagentRegistration | null): void {',
    '  if (!registration || registration.closed) return',
    '  const sessionManager = (ctx as { sessionManager?: { getSessionId?: () => unknown; getSessionFile?: () => unknown } } | null)?.sessionManager',
    '  const sessionId = sessionManager?.getSessionId?.()',
    '  const sessionFile = sessionManager?.getSessionFile?.()',
    "  const id = typeof sessionId === 'string' && sessionId ? sessionId : null",
    "  const file = typeof sessionFile === 'string' && sessionFile ? sessionFile : null",
    '  const key = file ?? id',
    '  if (!key) return',
    '  if (id && file) piAsyncSubagentMergeSessionKeys(id, file)',
    '  registration.sessionKey = key',
    '  piAsyncSubagentState.lastSession = key',
    '  piAsyncSubagentAdoptHeldRuns(registration, key)',
    '}',
    '',
    '// Why: only the runs THIS registration reported change hands, so one session’s start can never',
    '// adopt another’s children. Also used for a /reload the session survives: the registration',
    '// holding them stops being called, and the kept session is where they belong.',
    'function piAsyncSubagentAdoptHeldRuns(registration: PiAsyncSubagentRegistration | null, key: string | null): void {',
    '  if (!registration || !key) return',
    '  for (const entry of Array.from(piAsyncSubagentState.awaitingSession)) {',
    '    if (entry[1].registration !== registration) continue',
    '    piAsyncSubagentBucket(key).set(entry[0], entry[1])',
    '    piAsyncSubagentState.awaitingSession.delete(entry[0])',
    '  }',
    '}',
    '',
    '// Why: a session that ends without ever naming itself takes the children it reported with it —',
    '// they are not the next session’s, and holding them would pin a pane nobody can clear.',
    'function piAsyncSubagentDropHeldRuns(registration: PiAsyncSubagentRegistration | null): void {',
    '  if (!registration) return',
    '  for (const entry of Array.from(piAsyncSubagentState.awaitingSession)) {',
    '    if (entry[1].registration === registration) piAsyncSubagentState.awaitingSession.delete(entry[0])',
    '  }',
    '}',
    '',
    '// Why: where a run this registration reports belongs — the session it named, or the holding map',
    '// until its own context has named one.',
    'function piAsyncSubagentRunsForWrite(registration: PiAsyncSubagentRegistration): Map<string, PiAsyncSubagentRun> {',
    '  return registration.sessionKey ? piAsyncSubagentBucket(registration.sessionKey) : piAsyncSubagentState.awaitingSession',
    '}',
    '',
    '// Why: what a post rides. Explicit, so the ownership fields a run carries internally can never',
    '// reach the wire. Read at delivery, so a coalesced or retried post carries the current truth.',
    'function piAsyncSubagentRunWireList(runs: Map<string, PiAsyncSubagentRun> | undefined): Record<string, unknown>[] {',
    '  const out: Record<string, unknown>[] = []',
    '  for (const run of runs ? runs.values() : []) {',
    '    out.push({ id: run.id, ...(run.agent_type ? { agent_type: run.agent_type } : {}), ...(run.description ? { description: run.description } : {}) })',
    '  }',
    '  return out',
    '}',
    '',
    "// Why: the child set is pane STATE, not an event, and pi's transport keeps only the newest post —",
    '// the add a background spawn emits is overwritten by the tool burst that ends that same spawn.',
    '// Riding every post means whichever post survives carries the truth for the session on screen,',
    '// and a child of that pane which its session has not named itself yet is part of that truth.',
    'function piAsyncSubagentField(): Record<string, unknown> {',
    '  if (isOmpRuntime()) return {}',
    '  const key =',
    '    piAsyncSubagentActiveRegistration?.sessionKey ?? piAsyncSubagentSessionKey() ?? piAsyncSubagentState.lastSession',
    '  const bucket = key ? piAsyncSubagentState.bySession.get(key) : undefined',
    '  if (!bucket || bucket.size === 0) {',
    '    return { subagent_runs: piAsyncSubagentRunWireList(piAsyncSubagentState.awaitingSession) }',
    '  }',
    '  if (piAsyncSubagentState.awaitingSession.size === 0) {',
    '    return { subagent_runs: piAsyncSubagentRunWireList(bucket) }',
    '  }',
    '  const merged = new Map(bucket)',
    '  for (const entry of piAsyncSubagentState.awaitingSession) {',
    '    if (!merged.has(entry[0])) merged.set(entry[0], entry[1])',
    '  }',
    '  return { subagent_runs: piAsyncSubagentRunWireList(merged) }',
    '}',
    '',
    '// Why: a run’s own end removes it, and a workflow takes the children it launched with it — a',
    '// /reload drops the end signals of runs started before it, so nothing else can retire those. A',
    '// child THIS registration started still reports its own end and is not swept early by its parent.',
    'function piAsyncSubagentSweepRun(',
    '  registration: PiAsyncSubagentRegistration,',
    '  runs: Map<string, PiAsyncSubagentRun>,',
    '  runId: string',
    '): boolean {',
    '  if (!runs.delete(runId)) return false',
    '  for (const entry of Array.from(runs)) {',
    '    const child = entry[1]',
    '    if (child.parent !== runId || child.registration === registration) continue',
    '    piAsyncSubagentSweepRun(registration, runs, entry[0])',
    '  }',
    '  return true',
    '}',
    '',
    'function piAsyncSubagentRetireRun(registration: PiAsyncSubagentRegistration, runId: string): boolean {',
    '  // Why: a removal is looked for in the session this registration owns, the one on screen, the',
    '  // last one it served, and finally anywhere — the run it names HAS ended, and a bucket left',
    '  // unreachable by a session change would otherwise hold a finished child for good.',
    '  const key = registration.sessionKey ?? piAsyncSubagentSessionKey() ?? piAsyncSubagentState.lastSession',
    '  const preferred = key ? piAsyncSubagentState.bySession.get(key) : undefined',
    '  if (piAsyncSubagentSweepRun(registration, piAsyncSubagentState.awaitingSession, runId)) return true',
    '  if (preferred && piAsyncSubagentSweepRun(registration, preferred, runId)) return true',
    '  for (const bucket of piAsyncSubagentState.bySession.values()) {',
    '    if (bucket === preferred) continue',
    '    if (piAsyncSubagentSweepRun(registration, bucket, runId)) return true',
    '  }',
    '  return false',
    '}',
    '',
    '// Why: the bus is the identity, so a run handed the same `pi.events` it already armed finds the',
    '// binding rather than installing a second set of listeners on one channel.',
    'function piAsyncSubagentBindingForBus(bus: unknown): PiAsyncSubagentBusBinding | null {',
    "  if (!bus || typeof bus !== 'object') return null",
    '  for (const binding of piAsyncSubagentBusBindings) {',
    '    if (binding.bus === bus) return binding',
    '  }',
    '  return null',
    '}',
    '',
    '// Why: a shutdown closes exactly the callbacks its OWN registration installed — the binding it',
    '// owns — so a bus another registration armed keeps reporting. A registration whose shutdown marks',
    '// it closed is refused by the callbacks even where the bus cannot be unsubscribed from.',
    'function piAsyncSubagentCloseBus(registration: PiAsyncSubagentRegistration): void {',
    '  const index = piAsyncSubagentBusBindings.findIndex((binding) => binding.registration === registration)',
    '  if (index < 0) return',
    '  const binding = piAsyncSubagentBusBindings[index]',
    '  piAsyncSubagentBusBindings.splice(index, 1)',
    '  const bus = binding.bus as { off?: (channel: string, listener: (payload: unknown) => void) => void }',
    '  for (const entry of binding.listeners) {',
    '    bus.off?.(entry.channel, entry.listener)',
    '  }',
    '  binding.listeners = []',
    '}',
    ''
  ]
}
