import type { PiAgentKind } from '../../shared/pi-agent-kind'

/** Emitted into every Pi-family status extension: the fence that stops a session the pane does
 *  not own from reporting as it.
 *
 *  Both runtimes run a child agent as a second session in the pane's own process — OMP as an
 *  in-process task session, pi as a pi-subagents spawn (`createAgentSession`) — and both leave
 *  that child sharing the pane's `ORCA_PANE_KEY`, so its posts land on the pane. A child's
 *  `agent_end` would otherwise complete a pane whose lead is still working, so it has to be
 *  refused at the door.
 *
 *  Pane identity differs between them, and that is the whole reason this is two functions:
 *  OMP keeps one SessionManager across reload/new/resume, so its instance stands for the pane;
 *  pi REPLACES it on every one of those, so the pane is identified by the session FILE pi is on
 *  now, plus the file pi names when it hands the pane to its next session. The pi branch is
 *  emitted for `kind === 'pi'` only: no other family has evidence of an in-process child lane,
 *  and every other family keeps reporting exactly as it did before. */
export function getAgentStatusSessionOwnerHandlerSourceLines(kind: PiAgentKind): string[] {
  return [
    // SessionManager survives reload/new/resume; task children own a different instance.
    '  function sessionProvenance(ctx) {',
    '    const manager = ctx?.sessionManager',
    "    if (!manager || typeof manager !== 'object') return undefined",
    '    const id = typeof manager.getSessionId === "function" ? manager.getSessionId() : undefined',
    '    const file = typeof manager.getSessionFile === "function" ? manager.getSessionFile() : undefined',
    '    const header = typeof manager.getHeader === "function" ? manager.getHeader() : undefined',
    '    return { manager, id, file, parent: typeof header?.parentSession === "string" ? header.parentSession : undefined }',
    '  }',
    '',
    '  function normalizeSessionPath(file) {',
    '    const normalized = file.replace(/\\\\/g, "/")',
    '    return /^[A-Za-z]:\\//.test(normalized) ? normalized.toLowerCase() : normalized',
    '  }',
    '',
    '  function isNestedTaskTranscript(parentFile, candidateFile) {',
    '    if (typeof parentFile !== "string" || typeof candidateFile !== "string") return false',
    '    const parent = normalizeSessionPath(parentFile)',
    '    const candidate = normalizeSessionPath(candidateFile)',
    '    const root = parent.endsWith(".jsonl") ? parent.slice(0, -6) : parent',
    '    return candidate.startsWith(`${root}/`) && candidate !== parent',
    '  }',
    '',
    '  function ownsOmpSessionStatus(ctx) {',
    '    // Newer OMP builds may expose this computed runtime provenance directly.',
    '    if (ctx?.agentKind === "sub") return false',
    '    const current = sessionProvenance(ctx)',
    '    if (!current) return true',
    "    // A task transcript is never the pane's resumable root, even when its",
    '    // callback arrives before the root session reports on the shared hook.',
    '    if (current.parent) return false',
    '    // Keep ownership through module reload and shutdown while child sessions drain.',
    "    const key = Symbol.for('orca.omp.status-session-owners')",
    '    let owners = Reflect.get(globalThis, key)',
    '    if (!(owners instanceof Map)) {',
    '      owners = new Map()',
    '      Reflect.set(globalThis, key, owners)',
    '    }',
    '    const pane = JSON.stringify([process.env.ORCA_PANE_KEY, process.env.ORCA_AGENT_LAUNCH_TOKEN])',
    '    const owner = owners.get(pane)',
    '    if (owner) {',
    '      if (owner.manager === current.manager) return true',
    '      if (current.parent === owner.file || current.parent === owner.id) return false',
    '      if (isNestedTaskTranscript(owner.file, current.file)) return false',
    '      return false',
    '    }',
    '    owners.set(pane, current)',
    '    return true',
    '  }',
    '',
    ...(kind === 'pi' ? getPiPaneSessionFenceSourceLines() : []),
    '  function ownsSessionStatus(ctx, eventName, event) {',
    ...(kind === 'pi'
      ? [
          '    if (isOmpRuntime()) return ownsOmpSessionStatus(ctx)',
          '    return ownsPiSessionStatus(ctx, eventName, event)'
        ]
      : [
          '    // Why: only pi has an in-process child lane to fence; every other family keeps reporting.',
          '    if (!isOmpRuntime()) return true',
          '    return ownsOmpSessionStatus(ctx)'
        ]),
    '  }',
    '',
    '  function onStatus(name, handler) {',
    '    pi.on(name, (event, ctx) => {',
    '      if (!ownsSessionStatus(ctx, name, event)) return',
    '      lifecycleState.ownsPane = true',
    '      return handler(event, ctx)',
    '    })',
    '  }',
    '',
    "  onStatus('session_start', () => {})",
    ''
  ]
}

/** The pi half of the fence. Identity is the session FILE: pi replaces its SessionManager on
 *  /new, /fork and /resume, so the instance cannot stand for the pane the way it does for OMP. */
function getPiPaneSessionFenceSourceLines(): string[] {
  return [
    "  // The file this pane's own agent is on, plus the files already refused as its children,",
    '  // and the switch pi has announced but not yet reported. Process-global so a Pi reload —',
    '  // a fresh evaluation of this module — keeps the pane, and keyed by pane so two panes in',
    '  // one process never answer for each other.',
    '  function paneSessionEntry() {',
    "    const key = Symbol.for('orca.pi.status-pane-sessions')",
    '    let sessions = Reflect.get(globalThis, key)',
    '    if (!(sessions instanceof Map)) {',
    '      sessions = new Map()',
    '      Reflect.set(globalThis, key, sessions)',
    '    }',
    '    const pane = JSON.stringify([process.env.ORCA_PANE_KEY, process.env.ORCA_AGENT_LAUNCH_TOKEN])',
    '    let entry = sessions.get(pane)',
    '    if (!entry) {',
    '      entry = { file: undefined, claimed: false, handoff: undefined, switching: false, refused: new Set() }',
    '      sessions.set(pane, entry)',
    '    }',
    '    return entry',
    '  }',
    '',
    '  function adoptPaneSession(entry, file) {',
    '    entry.file = file',
    '    entry.claimed = true',
    '    entry.handoff = undefined',
    '    entry.switching = false',
    '  }',
    '',
    "  // Why: a session naming one of this pane's children as its parent is a nested child, and a",
    '  // session already refused never comes back as the pane it was refused for.',
    '  function refusesPaneSession(entry, current) {',
    '    if (current.parent !== undefined && (current.parent === entry.file || entry.refused.has(current.parent))) {',
    '      entry.refused.add(current.file)',
    '      return true',
    '    }',
    '    return false',
    '  }',
    '',
    '  // Why: pi-subagents runs a child agent as a second in-process session that shares this',
    "  // pane's key, so the child's agent_end must not complete the pane its lead is working in.",
    '  function ownsPiSessionStatus(ctx, eventName, event) {',
    '    const current = sessionProvenance(ctx)',
    '    const entry = paneSessionEntry()',
    '    const owned = current !== undefined && current.file !== undefined && current.file === entry.file',
    "    if (eventName === 'session_shutdown') {",
    "      // Why: only the pane's own session may say where the pane is going next; a child — with",
    '      // a session file of its own or an unpersisted one — never speaks for the pane it was',
    '      // spawned from. A runtime with no session manager cannot be attributed, so it is left alone.',
    '      if (!owned && current !== undefined && (current.file !== undefined || entry.file !== undefined)) {',
    '        return false',
    '      }',
    '      const reason = event?.reason',
    '      if (reason !== "new" && reason !== "fork" && reason !== "resume") return true',
    '      const target = event?.targetSessionFile',
    '      if (typeof target === "string" && target) entry.handoff = target',
    '      else entry.switching = true',
    '      return true',
    '    }',
    '    // Why: a runtime with no session manager cannot be keyed at all; keep reporting for it.',
    '    if (!current) return true',
    '    if (owned) return true',
    "    // Why: the first session to report is the pane's — persisted or not — and after that only",
    '    // a session pi hands over, or one naming the file the pane is leaving, may take the pane.',
    '    if (!entry.claimed) {',
    '      adoptPaneSession(entry, current.file)',
    '      return true',
    '    }',
    "    // Why: an unpersisted session is a nested child's, never the pane's once it has a file.",
    '    if (current.file === undefined) {',
    '      // Why: a switch to a file an unpersisted pane can never name must not stay open, or the',
    '      // next child that has a transcript would read it as the pane and take the pane for good.',
    '      entry.switching = false',
    '      return entry.file === undefined',
    '    }',
    '    // Why: pi says which file the pane moves to before the new session reports, and that',
    '    // outranks the parent link — a /fork names the file it forked from, exactly as a child does.',
    '    if (entry.handoff !== undefined && current.file === entry.handoff) {',
    '      adoptPaneSession(entry, current.file)',
    '      return true',
    '    }',
    "    // Why: a session_start naming the file the pane is leaving is the pane's own next session,",
    '    // so a switch this registration never saw still re-keys the pane — and, like the handoff',
    '    // above, it outranks the parent link, which a /fork sets to the very file it left.',
    '    // A reopened child instead names an older pane file, and falls through to be refused.',
    "    if (eventName === 'session_start' && entry.file !== undefined && event?.previousSessionFile === entry.file) {",
    '      adoptPaneSession(entry, current.file)',
    '      return true',
    '    }',
    '    // Why: a pi too old to name the file it is switching to still announces the switch; the',
    "    // next session_start is the pane's own there, and only there.",
    "    const switched = entry.switching === true && eventName === 'session_start'",
    '    if (entry.switching === true) entry.switching = false',
    '    if (switched) {',
    '      adoptPaneSession(entry, current.file)',
    '      return true',
    '    }',
    '    if (entry.refused.has(current.file)) return false',
    '    if (refusesPaneSession(entry, current)) return false',
    '    // A session that reports here without being the pane is a child of it, persisted or not.',
    '    entry.refused.add(current.file)',
    '    return false',
    '  }',
    ''
  ]
}
